export const hsCodeCountryMap = {
  "73079100": [
    "South Korea",
    "Spain",
    "Italy",
    "China",
    "India",
    "United Kingdom",
    "Other",
  ],
  "73079900": [
    "Thailand",
    "South Korea",
    "Italy",
    "China",
    "India",
    "United Kingdom",
    "Austria",
    "Saudi Arabia",
    "Taiwan",
    "Other",
  ],
  "73041900": [
    "Ukraine",
    "South Korea",
    "Italy",
    "China",
    "Argentina",
    "Germany",
    "Spain",
    "Brazil",
    "Romania",
    "South Africa",
    "India",
    "Japan",
    "UAE",
    "Other",
  ],
  "73072100": [
    "Germany",
    "Italy",
    "India",
    "China",
    "United Kingdom",
    "Netherlands",
    "Other",
  ],
  "73072900": [
    "Thailand",
    "Austria",
    "South Korea",
    "Germany",
    "China",
    "India",
    "Italy",
  ],
  "73044100": [
    "China",
    "India",
    "Spain",
    "Italy",
    "Taiwan",
    "Germany",
    "Japan",
    "Netherlands",
    "Other",
  ],
  "84841000": ["India", "China", "Italy", "Germany", "Other"],
  "73181500": ["India", "China", "South Korea", "UAE", "Other"],
  "84818040": ["India", "China", "Italy", "Spain", "Germany", "Other"],
};

export const hsCodeLabels = {
  "73079100": "CS FLANGES",
  "73079900": "CS FITTINGS / SPECTACLE BLIND",
  "73041900": "CS PIPE",
  "73072100": "SS FLANGES",
  "73072900": "SS FITTINGS",
  "73044100": "SS PIPE",
  "84841000": "GASKET",
  "73181500": "STUD BOLT",
  "84818040": "VALVE",
};
